name: Build and Deploy Static Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PYTHON_VERSION: '3.11'

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build static site with Flask-Freeze
        run: |
          python freeze.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build  # Adjust if your output directory is different

  deploy:
    name: Deploy Site
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write      # To deploy to GitHub Pages
      id-token: write   # To authenticate the deployment

    steps:
      - name: Deploy to GitHub Pages 🚀
        uses: actions/deploy-pages@v1
